// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	processes "github.com/anti-duhring/autojud/internal/processes"
	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryProcesses is an autogenerated mock type for the Repository type
type MockRepositoryProcesses struct {
	mock.Mock
}

type MockRepositoryProcesses_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryProcesses) EXPECT() *MockRepositoryProcesses_Expecter {
	return &MockRepositoryProcesses_Expecter{mock: &_m.Mock}
}

// CountByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryProcesses) CountByUserID(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryProcesses_CountByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserID'
type MockRepositoryProcesses_CountByUserID_Call struct {
	*mock.Call
}

// CountByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryProcesses_Expecter) CountByUserID(ctx interface{}, userID interface{}) *MockRepositoryProcesses_CountByUserID_Call {
	return &MockRepositoryProcesses_CountByUserID_Call{Call: _e.mock.On("CountByUserID", ctx, userID)}
}

func (_c *MockRepositoryProcesses_CountByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryProcesses_CountByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryProcesses_CountByUserID_Call) Return(_a0 int, _a1 error) *MockRepositoryProcesses_CountByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryProcesses_CountByUserID_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRepositoryProcesses_CountByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePendingProcess provides a mock function with given fields: ctx, processID
func (_m *MockRepositoryProcesses) CreatePendingProcess(ctx context.Context, processID string) (*processes.PendingProcess, error) {
	ret := _m.Called(ctx, processID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePendingProcess")
	}

	var r0 *processes.PendingProcess
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*processes.PendingProcess, error)); ok {
		return rf(ctx, processID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *processes.PendingProcess); ok {
		r0 = rf(ctx, processID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*processes.PendingProcess)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, processID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryProcesses_CreatePendingProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePendingProcess'
type MockRepositoryProcesses_CreatePendingProcess_Call struct {
	*mock.Call
}

// CreatePendingProcess is a helper method to define mock.On call
//   - ctx context.Context
//   - processID string
func (_e *MockRepositoryProcesses_Expecter) CreatePendingProcess(ctx interface{}, processID interface{}) *MockRepositoryProcesses_CreatePendingProcess_Call {
	return &MockRepositoryProcesses_CreatePendingProcess_Call{Call: _e.mock.On("CreatePendingProcess", ctx, processID)}
}

func (_c *MockRepositoryProcesses_CreatePendingProcess_Call) Run(run func(ctx context.Context, processID string)) *MockRepositoryProcesses_CreatePendingProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryProcesses_CreatePendingProcess_Call) Return(_a0 *processes.PendingProcess, _a1 error) *MockRepositoryProcesses_CreatePendingProcess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryProcesses_CreatePendingProcess_Call) RunAndReturn(run func(context.Context, string) (*processes.PendingProcess, error)) *MockRepositoryProcesses_CreatePendingProcess_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProcess provides a mock function with given fields: ctx, process
func (_m *MockRepositoryProcesses) CreateProcess(ctx context.Context, process *processes.Process) (*processes.Process, error) {
	ret := _m.Called(ctx, process)

	if len(ret) == 0 {
		panic("no return value specified for CreateProcess")
	}

	var r0 *processes.Process
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *processes.Process) (*processes.Process, error)); ok {
		return rf(ctx, process)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *processes.Process) *processes.Process); ok {
		r0 = rf(ctx, process)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*processes.Process)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *processes.Process) error); ok {
		r1 = rf(ctx, process)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryProcesses_CreateProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProcess'
type MockRepositoryProcesses_CreateProcess_Call struct {
	*mock.Call
}

// CreateProcess is a helper method to define mock.On call
//   - ctx context.Context
//   - process *processes.Process
func (_e *MockRepositoryProcesses_Expecter) CreateProcess(ctx interface{}, process interface{}) *MockRepositoryProcesses_CreateProcess_Call {
	return &MockRepositoryProcesses_CreateProcess_Call{Call: _e.mock.On("CreateProcess", ctx, process)}
}

func (_c *MockRepositoryProcesses_CreateProcess_Call) Run(run func(ctx context.Context, process *processes.Process)) *MockRepositoryProcesses_CreateProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*processes.Process))
	})
	return _c
}

func (_c *MockRepositoryProcesses_CreateProcess_Call) Return(_a0 *processes.Process, _a1 error) *MockRepositoryProcesses_CreateProcess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryProcesses_CreateProcess_Call) RunAndReturn(run func(context.Context, *processes.Process) (*processes.Process, error)) *MockRepositoryProcesses_CreateProcess_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProcessFollow provides a mock function with given fields: ctx, processID, userID
func (_m *MockRepositoryProcesses) CreateProcessFollow(ctx context.Context, processID string, userID string) (*processes.ProcessFollow, error) {
	ret := _m.Called(ctx, processID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProcessFollow")
	}

	var r0 *processes.ProcessFollow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*processes.ProcessFollow, error)); ok {
		return rf(ctx, processID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *processes.ProcessFollow); ok {
		r0 = rf(ctx, processID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*processes.ProcessFollow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, processID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryProcesses_CreateProcessFollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProcessFollow'
type MockRepositoryProcesses_CreateProcessFollow_Call struct {
	*mock.Call
}

// CreateProcessFollow is a helper method to define mock.On call
//   - ctx context.Context
//   - processID string
//   - userID string
func (_e *MockRepositoryProcesses_Expecter) CreateProcessFollow(ctx interface{}, processID interface{}, userID interface{}) *MockRepositoryProcesses_CreateProcessFollow_Call {
	return &MockRepositoryProcesses_CreateProcessFollow_Call{Call: _e.mock.On("CreateProcessFollow", ctx, processID, userID)}
}

func (_c *MockRepositoryProcesses_CreateProcessFollow_Call) Run(run func(ctx context.Context, processID string, userID string)) *MockRepositoryProcesses_CreateProcessFollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryProcesses_CreateProcessFollow_Call) Return(_a0 *processes.ProcessFollow, _a1 error) *MockRepositoryProcesses_CreateProcessFollow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryProcesses_CreateProcessFollow_Call) RunAndReturn(run func(context.Context, string, string) (*processes.ProcessFollow, error)) *MockRepositoryProcesses_CreateProcessFollow_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockRepositoryProcesses) GetAllByUserID(ctx context.Context, userID string, limit int, offset int) ([]*processes.Process, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []*processes.Process
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*processes.Process, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*processes.Process); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*processes.Process)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryProcesses_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockRepositoryProcesses_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockRepositoryProcesses_Expecter) GetAllByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockRepositoryProcesses_GetAllByUserID_Call {
	return &MockRepositoryProcesses_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", ctx, userID, limit, offset)}
}

func (_c *MockRepositoryProcesses_GetAllByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockRepositoryProcesses_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRepositoryProcesses_GetAllByUserID_Call) Return(_a0 []*processes.Process, _a1 error) *MockRepositoryProcesses_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryProcesses_GetAllByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*processes.Process, error)) *MockRepositoryProcesses_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProcessNumber provides a mock function with given fields: ctx, processNumber
func (_m *MockRepositoryProcesses) GetByProcessNumber(ctx context.Context, processNumber string) (*processes.Process, error) {
	ret := _m.Called(ctx, processNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByProcessNumber")
	}

	var r0 *processes.Process
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*processes.Process, error)); ok {
		return rf(ctx, processNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *processes.Process); ok {
		r0 = rf(ctx, processNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*processes.Process)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, processNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryProcesses_GetByProcessNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProcessNumber'
type MockRepositoryProcesses_GetByProcessNumber_Call struct {
	*mock.Call
}

// GetByProcessNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - processNumber string
func (_e *MockRepositoryProcesses_Expecter) GetByProcessNumber(ctx interface{}, processNumber interface{}) *MockRepositoryProcesses_GetByProcessNumber_Call {
	return &MockRepositoryProcesses_GetByProcessNumber_Call{Call: _e.mock.On("GetByProcessNumber", ctx, processNumber)}
}

func (_c *MockRepositoryProcesses_GetByProcessNumber_Call) Run(run func(ctx context.Context, processNumber string)) *MockRepositoryProcesses_GetByProcessNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryProcesses_GetByProcessNumber_Call) Return(_a0 *processes.Process, _a1 error) *MockRepositoryProcesses_GetByProcessNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryProcesses_GetByProcessNumber_Call) RunAndReturn(run func(context.Context, string) (*processes.Process, error)) *MockRepositoryProcesses_GetByProcessNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryProcesses creates a new instance of MockRepositoryProcesses. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryProcesses(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryProcesses {
	mock := &MockRepositoryProcesses{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
