package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	graphql1 "github.com/anti-duhring/autojud/internal/generated/graphql"
)

// FollowProcess is the resolver for the FollowProcess field.
func (r *mutationResolver) FollowProcess(ctx context.Context, processNumber string) (*graphql1.Process, error) {
	panic(fmt.Errorf("not implemented: FollowProcess - FollowProcess"))
}
